#!/bin/bash

if [ ! -s /tmp/emerge.out ] ; then
    exit 0
fi

grep -q '*' /tmp/emerge.out
if [ $? -eq 0 ] ; then
  /home/doug/bin/cron_tweet "Problem with automatic emerge"
  rm /tmp/emerge.out
  exit 0
fi

grep -q '!' /tmp/emerge.out
if [ $? -eq 0 ] ; then
  /home/doug/bin/cron_tweet "Problem with automatic emerge"
  rm /tmp/emerge.out
  exit 0
fi

grep -q kde-meta /tmp/emerge.out
if [ $? -eq 0 ] ; then
	grep -v kde-base /tmp/emerge.out > /tmp/emerge.out2
	grep kde-meta /tmp/emerge.out >> /tmp/emerge.out2
	mv /tmp/emerge.out2 /tmp/emerge.out
fi

while read line
do
  action=`echo "$line" | cut -c1-6 | tr -d ' '`
  package=`echo "$line" | cut -c7- | awk '{print $1}'`
  version=`echo "$line" | cut -c7- | awk '{print $2}'`

  case $action in
    N*)
      action="Installing"
      verb=
      ;;
    U)
      action="Upgrading"
      verb=to
      ;;
    UD|D)
      action='Downgrading'
      verb=to
      ;;
    R|rR|r)
      action='Replacing'
      verb=
      ;;
  esac

  /home/doug/bin/cron_tweet "$action $package $verb $version"
  sleep 30
done < /tmp/emerge.out
