#!/bin/bash

# Copyright Douglas J Hunley 2013

# Run a test emerge of @world to see if there are updates and record the same for later
/usr/bin/emerge --update --pretend \
  --columns \
  --color n \
  --nospinner \
  --unordered-display \
  --newuse \
  --deep \
  --with-bdeps y \
  --quiet @world &> /tmp/emerge.out
