#!/bin/bash

# Copyright Douglas J Hunley 2012

# I *love* Bash tab completion, so I want it enabled by default for every installed
# package that supports it. To that end:
# list all available completions
/usr/bin/eselect bashcomp list | grep '\[' | awk '{print $1}' | tr -d '[' | tr -d ']' | while read line
do
  # and turn them on
  /usr/bin/eselect bashcomp enable --global $line 2>&1 | grep -v already
done
# and clean up some cruft that gets created
rm -f /etc/bash_completion.d/Makefile.*
